Repository Sassy-Software-Engineers/Grace-Shopper, pull requests merged in 2022-08, with the labels that each got.

#82 create assignedissues.yml file
  .github/workflows/assignedIssues.yml
Labels: enhancement, ready_for_review

#81 Add .github folder for issue templates and workflow files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, ready_for_review

#89 Seed file-- Read description before approval ;)
  .env
  .github/workflows/webhooks.md
  script/seed.js
Labels: bug, ready_for_review

#84 isAdmin added, product put and post routes
  server/api/middlewares.js
  server/api/products.js
  server/api/users.js
Labels: ready_for_review

#87 admin file folder and admin component
  client/components/Admin/Admin.js
  client/components/Admin/AdminInformationPage.js
  client/components/Admin/EditAdminInfo.js
  client/components/Admin/EditProduct.js
  client/components/Admin/OrderList.js
  client/components/Admin/ProductsList.js
  client/components/Admin/UserList.js
Labels: ready_for_review

#83 Cart items express
  server/api/cartItems.js
  server/db/models/Order.js
Labels: ready_for_review

#102 fixes to db/models Product and Order files
  server/db/models/Order.js
  server/db/models/Product.js
Labels: ready_for_review

#113 ReadMe issue#53
  README.md
Labels: ready_for_review

#121 closes issue #70
  CONTRIBUTING.md
  NORMS.md
  README.md
  client/components/Admin/EditProduct.js
  client/components/Product/EditProduct.js
Labels: ready_for_review

#124 added wireframes
  Wireframing/wires.md
Labels: ready_for_review

#130 bootstrappp
  CONTRIBUTING.md
  README.md
  client/index.js
  public/index.html
Labels: ready_for_review

#137 container wrapper and installed bootstraps
  client/index.js
  public/style.css
Labels: ready_for_review
